# Generated by Django 2.0 on 2017-12-04 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_auto_20171204_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='penalizaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_cre',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 20, 26, 11, 933855, tzinfo=utc)),
        ),
    ]
