# Generated by Django 2.0 on 2017-12-04 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_auto_20171204_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='art_apro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='art_rech',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_cre',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 20, 54, 22, 375677, tzinfo=utc)),
        ),
    ]
